### ISSUE TITLE
Suggestion: Remove call to powf for square

### ISSUE THREAD

**Issue by Bl00drav3n** [glouw/tinn#10]
Hi! Just a quick suggestion regarding performance when calling err
https://github.com/glouw/tinn/blob/e92adf34e808b1c47cb2f1b42092ae806e5f4982/Tinn.c#L11

Instead of calling powf from the standard library, it would be nicer to just call an inline square() function, or even better, use a macro (I couldn't convince visual studio to actually remove the call instruction otherwise). 

For example a call to powf on my machine results in a call to _libm_sse2_pow_precise which has more than 50 instructions until it returns, when what you really want is just one single mul instruction.

I realize that it might not really be that big of a deal, because calls to err only scale with output and iteration size, but making the change is super trivial.

I did a quick test anyway on my i7-7700K with Visual Studio 2017 and /O2 optimization enabled. Using a simple SQUARE(x) macro resulted in a 2.6% speed improvement per call to xttrain, while using a call to a square(x) function resulted in a 1.8% speed improvement. This will only get better as the number of iterations and ouputs grow.

**Comment by nsauzede** [comment]
+1
Would you mind creating a pull-request with this simple yet useful perf fix ?

**Comment by glouw** [comment]
If you're on linux test with valgrind:

valgrind --tool=cachegrind ./tinn

With both powf and the macro method. See which one yields fewer instruction counts and I'll accept the pull

**Comment by nsauzede** [comment]
I had some time to experiment more and perform the cachegrind test : both instr counts are the same !
And for a reason : it seems like Ubuntu17.10 gcc-7.2.0 -Ofast already optimizes powf(x,2.0) : 

> (gdb) l err
9	`/*static*/` float err(const float a, const float b)
10	{
11	    return 0.5f * powf(a - b, 2.0f);
(gdb) disas err
Dump of assembler code for function err:
   0x0000000000003150 <+0>:	vsubss %xmm1,%xmm0,%xmm0
   0x0000000000003154 <+4>:	vmulss %xmm0,%xmm0,%xmm0
   0x0000000000003158 <+8>:	vmulss 0x1e8(%rip),%xmm0,%xmm0        # 0x3348
   0x0000000000003160 <+16>:	retq

**Comment by nsauzede** [comment]
Anyway, I think it's good to have replaced powf call by the hardcoded multiply : because the intent is **explicit**, and the optimization comes **for free** even for compilers that don't do it, unlike above..
I re-run cachegrind without -Ofast and the insn counts are slightly different (~0.066% gain), although of course, both codes with and without powf call are thus non-optimized

**Comment by glouw** [comment]
The 0.066% gain you see in cachegrind is likely due to variance in the simulated branch predictor.

I agree, SQUARE is best. I don't think embedded compilers for ARM and AVR are smart enough to know powf(x, 2.0) == x * x

**Comment by Bl00drav3n** [comment]
As I noted, Visual Studio's compiler is not smart enough and will generate code that plows through a whole bunch of in this case useless instructions. @nsauzede I did a similar test yesterday with Windows 10's Ubuntu subsystem and got a similar result using gcc -Ofast. Really nice that gcc is smart enough to replace it!

**Comment by glouw** [comment]
you're right, sometimes its best to program for the slowest machine

**Comment by nsauzede** [comment]
@Bl00drav3n Offtopic : do you have some pointers on how to experiment with Windows 10's Ubuntu subsystem ?

**Comment by glouw** [comment]
If you're on windows you cant go wrong with the MinGW / MSYS route.

**Comment by nsauzede** [comment]
it was off-topic, just to know how to experiment with Ubuntu subsystem of Windows 10 (for @Bl00drav3n )
@glouw I guess you can safely resolve/close this issue, now that the #11 is merged

**Comment by Bl00drav3n** [comment]
@nsauzede I don't know what you're specifically asking about, but this might help: [Windows 10 Installation Guide](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
@glouw Thanks for the discussion, I guess I'll go ahead and close this thread now. :)

**Comment by nsauzede** [comment]
Thanks for the pointer, @Bl00drav3n !!
