### ISSUE TITLE
Add vcxproj for native Windows builds

### ISSUE THREAD

**Issue by swaldhoer** [glouw/tinn#14]
I added a `vcxproj` file to build natively on Windows, as this might be nice for Windows developers (see
https://github.com/swaldhoer/tinn/commit/e445817731c2079a64a7cfc0028f49eb224f3b80)

If you are interest I will make a pull request.

**Comment by glouw** [comment]
mingw32 is currently supported in the makefile. I don't plan to add anymore build methods as the library is just a single .c and .h file
