### ISSUE TITLE
Questions about bias

### ISSUE THREAD

**Issue by himcrh** [glouw/tinn#29]
Hi!
Great library!
But have questions like:
`t.h[i] = act(sum + t.b[0]);`
`t.o[i] = act(sum + t.b[1]);`
Why only have one fixed bias for all the nets?
Maybe there's some misunderstanding.
Looking forward to your reply.

**Comment by glouw** [comment]
I believe that since it's a single layer feed forward neural network only one layer of bias is needed.

**Comment by himcrh** [comment]
I understand ... The bias won't be updated.
Thanks.
