### ISSUE TITLE
Could we have an example on the readme on how to use the semeion.data?

### ISSUE THREAD

**Issue by hamoym** [glouw/tinn#5]
I successfully compile the program using make but I don't know what are the options to use the data on example link. 

Thank you so much.

**Comment by dvdplm** [comment]
I second @hamoym and to add to that: perhaps clarify what the output numbers of the example mean? Thanks! :)

**Comment by warmwaffles** [comment]
You should check out the https://github.com/glouw/tinn/blob/master/test.c file. It has a high level test and should get you rolling.

**Comment by glouw** [comment]
test.c oughta do it. Its got some extra fluff for loading data from a text file - a part that Tinn doesn't care for - loading and parsing files is up to the programmer.

As for the data test.c uses, its from the machine learning repository:

https://archive.ics.uci.edu/ml/datasets/semeion+handwritten+digit

Each line in the dataset represents one black on white hand written digit. The first 256 digits of the line is the binary representation of a digit (16x16 display, 1 is a black pixel, 0 is a white pixel). The last 10 digits of each line is the corresponding number.

For example:

3: 0 0 0 1 0 0 0 0 0 0
6: 0 0 0 0 0 0 1 0 0 0

And so on.

For test.c, this gives 256 for nips, and 10 for nops.

nhid is your choice, as well as learning rate and anneal. You can get away with keeping anneal at 1.0.

sranding and shuffling is up to you but not totally needed if you're looking to get something quickly.

**Comment by glouw** [comment]
I should mention at the end of test.c it prints one actual output and the predicted output like so:
```

0.000000 0.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000 0.000000 
0.001402 0.000011 0.000002 0.004343 0.001983 0.999266 0.003902 0.000024 0.000039 0.003032 

```

The number here is 5, and the prediction is 99.9266% that its 5.

**Comment by warmwaffles** [comment]
@glouw probably add a lil blurb to the readme about just running the test.c and inspecting the results would suffice.

**Comment by glouw** [comment]
Sure thing

**Comment by glouw** [comment]
Updated the readme with tips on semeion, as well as a more general xor example.

**Comment by hamoym** [comment]
Thank you @glouw !
