### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by JuPrgn** [glouw/tinn#7]
Hi,

Thank you for your library I was looking for this from long time !

Anyway I do not succeed using your example on number recognition, I get wrong results and can't figure out why : 
1.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 
0.624335 0.837375 0.552968 0.280362 0.601309 0.397255 0.634169 0.425480 0.439418 0.132246 

Julien

**Comment by glouw** [comment]
strange, are you on windows? did you modify test.c at all?

**Comment by nsauzede** [comment]
I noticed the same issue on Windows with MSYS2/Mingw64
I made a fix for this in pull-request #8

**Comment by nsauzede** [comment]
This is due to Mingw64 implementation of printf/scanf %a format support apparently requiring additional "-posix" flag in CFLAGS
Sigh..

**Comment by glouw** [comment]
What a happy time. Thanks for finding this. I think its best we go %f instead of %a for printf() and scanf() to keep things portable. Mind testing %f without the -posix flag?

**Comment by nsauzede** [comment]
Yes I can test the %f variant..

**Comment by JuPrgn** [comment]
Thank you for your answers I am using MinGW32 from QT 5.9 I will give it a look.

**Comment by nsauzede** [comment]
Just tested : go for it (%f instead of %a, without -posix)
%f does not seem to loose much precision indeed...
using %f hence is more portable and more "minimalist" (less Makefile/compiler burden)
if you want I cant create another pull-request now that I just did it

**Comment by JuPrgn** [comment]
Where are these %a you are talking about ?

**Comment by glouw** [comment]
Yes please, I'll take the new %f pull request without -posix

**Comment by nsauzede** [comment]
@JuTakata  in Tinn.c
these are the floating point format used to serialize/deserialize values to/from files

**Comment by JuPrgn** [comment]
I tried with -posix but I still have funky results

**Comment by JuPrgn** [comment]
Replacing %a with %f solved this issue ! Great job =)

**Comment by glouw** [comment]
Master has the change in too. Thanks ju and ns.

**Comment by JuPrgn** [comment]
Thank you glouw and ns for you fast support !
